# Generated by Django 5.0.3 on 2024-03-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_reviewrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
